//! The one rule that decides which Argon2id cost a build of DCTL writes.
//!
//! This file is compiled **twice** — once as part of the crate, and once by
//! `build.rs`, which pulls it in with `#[path]`. That is deliberate: the rule
//! and the code that applies it are the same lines rather than two copies that
//! can drift apart, and the rule is therefore unit-testable without running a
//! build script.
//!
//! ## The problem this exists to solve
//!
//! The test suite needs a vault it can open in microseconds. A shipped vault
//! needs one that costs an attacker 128 MiB and three passes for every password
//! guess. Both cannot be true of one set of numbers, so the numbers have to
//! depend on the build — and the moment that is true, the question becomes *who
//! can choose*.
//!
//! It has to be nobody. An envelope records its own KDF parameters
//! (`docs/FORMAT.md` §2), which is what makes a cheaply-written vault readable
//! forever; it is also what makes one permanently weak. A vault created under
//! reduced parameters has a brute-forceable password and no way to notice, so a
//! build that can be *talked into* writing them is a build that can be talked
//! into creating that vault.
//!
//! ## Why every obvious mechanism is disqualified
//!
//! * A **Cargo feature** can be enabled from the command line (`--features`),
//!   and feature unification means any crate in the graph can enable it for
//!   everyone else.
//! * An **environment variable** read at run time is chosen by whoever runs the
//!   binary — precisely the person Argon2id is defending against.
//! * A **CLI flag** is worse still, because it is documented.
//! * Even **`cfg(debug_assertions)`** is settable in a release build, by
//!   `RUSTFLAGS="-C debug-assertions=on"` or by `[profile.release]
//!   debug-assertions = true`.
//! * Any **custom `cfg`** is settable the same way, with `--cfg`.
//!
//! Cargo's `PROFILE` has none of those properties. Cargo computes it from the
//! profile actually in use, hands it to build scripts only, and does not let it
//! be overridden: exporting `PROFILE=debug` before `cargo build --release`
//! still reports `release`, and so does a release build with debug assertions
//! forced on. `tests/kdf_cost.rs` pins that by building a probe crate under
//! each of those conditions and reading what its build script saw — if a future
//! Cargo ever changes it, the suite says so rather than the vaults getting
//! quietly cheap.
//!
//! And the decision is baked into **generated source**, not into a `cfg`, so
//! `--cfg` on the command line has nothing to flip either.
//!
//! The guarantee is therefore not "hard to set". It is "nothing to set": the
//! reduced cost can be reached only by editing this file and rebuilding.

/// The value Cargo reports in `PROFILE` for a build that is **not** shipped.
///
/// Cargo reports exactly two words. `debug` covers the `dev` and `test`
/// profiles — the ones `cargo build` and `cargo test` use, and the only ones a
/// reduced cost is for.
pub const CARGO_DEBUG_PROFILE: &str = "debug";

/// The value Cargo reports in `PROFILE` for a shipped build.
///
/// Reported for `--release` **and** for any custom profile that inherits from
/// it, which is what lets a distributor invent a profile name without this file
/// having to learn it.
pub const CARGO_RELEASE_PROFILE: &str = "release";

/// File name `build.rs` writes into `OUT_DIR`, and `kdf::cost` includes.
pub const GENERATED_FILE: &str = "kdf_cost_profile.rs";

/// Name of the constant inside [`GENERATED_FILE`].
pub const GENERATED_CONST: &str = "WRITES_PRODUCTION_COST";

/// Whether a build Cargo describes as `profile` writes the production cost.
///
/// **Fails closed.** Only the one word Cargo uses for an unoptimized build
/// turns the production cost off; an absent, empty or unrecognised profile —
/// including any name a future Cargo might invent — is treated as a shipped
/// build. The failure mode of guessing wrong is a slow test suite in one
/// direction and a brute-forceable vault in the other, so the default is the
/// slow one.
#[must_use]
pub fn writes_production_cost(profile: Option<&str>) -> bool {
    profile != Some(CARGO_DEBUG_PROFILE)
}

/// The Rust source `build.rs` writes into `OUT_DIR` for `kdf::cost` to include.
///
/// Generated as source rather than emitted as a `cargo::rustc-cfg` because a
/// `cfg` can be set a second way — `RUSTFLAGS="--cfg …"` — and a security gate
/// with two inputs has one too many.
#[must_use]
pub fn generated_source(writes_production_cost: bool) -> String {
    format!(
        "// @generated by dctl-crypto/build.rs from Cargo's PROFILE. Do not edit.\n\
         //\n\
         // `true` means this build writes `Cost::PRODUCTION` into every new vault.\n\
         // See `dctl_crypto::kdf::gate` for why this is generated source and not a `cfg`.\n\
         const {GENERATED_CONST}: bool = {writes_production_cost};\n"
    )
}
